2022-07-17 21:29:47,120 ERROR: Exception on /create_asset [GET] [in /Users/philhome/flask_sem/venv/lib/python3.8/site-packages/flask/app.py:1449]
Traceback (most recent call last):
  File "/Users/philhome/flask_sem/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/philhome/flask_sem/venv/lib/python3.8/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/philhome/flask_sem/venv/lib/python3.8/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/philhome/flask_sem/venv/lib/python3.8/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/philhome/flask_sem/app/routes.py", line 109, in create_asset
    return render_template('create_asset.html', title='Create Asset', form=form)
  File "/Users/philhome/flask_sem/venv/lib/python3.8/site-packages/flask/templating.py", line 154, in render_template
    return _render(
  File "/Users/philhome/flask_sem/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/philhome/flask_sem/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/philhome/flask_sem/venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/philhome/flask_sem/app/templates/create_asset.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/philhome/flask_sem/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/philhome/flask_sem/app/templates/create_asset.html", line 8, in block 'content'
    {{ form.asset_name.label }}<br>
  File "/Users/philhome/flask_sem/venv/lib/python3.8/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.forms.CreateAssetForm object' has no attribute 'asset_name'
2022-07-17 21:29:47,803 ERROR: Exception on /create_asset [GET] [in /Users/philhome/flask_sem/venv/lib/python3.8/site-packages/flask/app.py:1449]
Traceback (most recent call last):
  File "/Users/philhome/flask_sem/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/philhome/flask_sem/venv/lib/python3.8/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/philhome/flask_sem/venv/lib/python3.8/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/philhome/flask_sem/venv/lib/python3.8/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/philhome/flask_sem/app/routes.py", line 109, in create_asset
    return render_template('create_asset.html', title='Create Asset', form=form)
  File "/Users/philhome/flask_sem/venv/lib/python3.8/site-packages/flask/templating.py", line 154, in render_template
    return _render(
  File "/Users/philhome/flask_sem/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/philhome/flask_sem/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/philhome/flask_sem/venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/philhome/flask_sem/app/templates/create_asset.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/philhome/flask_sem/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/philhome/flask_sem/app/templates/create_asset.html", line 8, in block 'content'
    {{ form.asset_name.label }}<br>
  File "/Users/philhome/flask_sem/venv/lib/python3.8/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.forms.CreateAssetForm object' has no attribute 'asset_name'
2022-07-17 21:29:49,738 ERROR: Exception on /create_asset [GET] [in /Users/philhome/flask_sem/venv/lib/python3.8/site-packages/flask/app.py:1449]
Traceback (most recent call last):
  File "/Users/philhome/flask_sem/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/philhome/flask_sem/venv/lib/python3.8/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/philhome/flask_sem/venv/lib/python3.8/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/philhome/flask_sem/venv/lib/python3.8/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/philhome/flask_sem/app/routes.py", line 109, in create_asset
    return render_template('create_asset.html', title='Create Asset', form=form)
  File "/Users/philhome/flask_sem/venv/lib/python3.8/site-packages/flask/templating.py", line 154, in render_template
    return _render(
  File "/Users/philhome/flask_sem/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/philhome/flask_sem/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/philhome/flask_sem/venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/philhome/flask_sem/app/templates/create_asset.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/philhome/flask_sem/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/philhome/flask_sem/app/templates/create_asset.html", line 8, in block 'content'
    {{ form.asset_name.label }}<br>
  File "/Users/philhome/flask_sem/venv/lib/python3.8/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.forms.CreateAssetForm object' has no attribute 'asset_name'
2022-07-18 18:52:16,155 INFO: Indie Research startup [in /Users/philhome/flask_sem/app/__init__.py:50]
